import Link from "next/link";

export const metadata = { title: "Privacy Policy | MySales", description: "Privacy Policy for MySales." };

export default function LegalPage() {
 return <>
  <header className="legal-nav"><Link href="/" className="legal-brand"><span className="legal-mark">M</span><span>MY<span>SALES</span></span></Link><Link href="/" className="legal-back">← Back to MySales</Link></header>
  <main className="legal-page"><h1>Privacy Policy</h1>
<p className="legal-updated"><strong>Last Updated: August 9, 2026</strong></p>
<h2>1. Introduction</h2><p>Welcome to <strong>mysales</strong> ("we", "our", or "us"). We respect your privacy and are committed to protecting the information you provide when using our application.</p><p>This Privacy Policy explains what information we collect, how we use it, how we protect it, and your rights regarding your information.</p><p>By using mysales, you agree to the practices described in this Privacy Policy.</p>
<h2>2. Information We Collect</h2><p>Depending on how you use mysales, we may collect the following information:</p>
<h3>Account Information</h3><ul><li>Your name</li><li>Email address</li><li>Phone number</li><li>Password or authentication information</li></ul>
<h3>Business Information</h3><ul><li>Business name</li><li>Business address</li><li>Products and services</li><li>Product prices</li><li>Sales records</li><li>Customer information</li><li>Staff information</li><li>Inventory information</li></ul>
<h3>Transaction Information</h3><ul><li>Products sold</li><li>Quantities</li><li>Prices</li><li>Discounts</li><li>Payment information or payment status</li><li>Date and time of transactions</li><li>Customer information associated with transactions</li></ul>
<h3>Device and Usage Information</h3><ul><li>Device type</li><li>Operating system</li><li>Application version</li><li>IP address</li><li>Error and diagnostic information</li><li>Information about how you interact with the application</li></ul>
<h2>3. How We Use Your Information</h2><ul><li>Create and manage your account</li><li>Provide and operate mysales</li><li>Store and display your business records</li><li>Process and manage sales information</li><li>Provide inventory and business management features</li><li>Improve the application</li><li>Maintain security</li><li>Detect and prevent fraud or abuse</li><li>Fix technical problems</li><li>Communicate important information about the service</li><li>Provide customer support</li></ul><p>We do not sell your personal information to third parties.</p>
<h2>4. How We Store Your Information</h2><p>Your information may be stored using third-party infrastructure and cloud service providers that help us operate mysales.</p><p>We take reasonable technical and organizational measures to protect your information from unauthorized access, loss, misuse, alteration, or disclosure. However, no internet-based service can guarantee absolute security.</p>
<h2>5. Sharing of Information</h2><p>We may share information only when reasonably necessary to operate mysales, including with cloud hosting and database providers, authentication providers, payment providers where applicable, analytics or technical service providers where applicable, and legal authorities when required by law.</p><p>We do not sell or rent your personal information.</p>
<h2>6. Payment Information</h2><p>If mysales provides payment-related features, payments may be processed by third-party payment providers. We do not intend to store your complete card details or banking credentials unless explicitly stated within the relevant service. Payment providers may collect and process payment information according to their own privacy policies.</p>
<h2>7. Customer and Business Data</h2><p>mysales may allow you to enter information about your customers, employees, suppliers, and other individuals. You are responsible for ensuring that you have the appropriate rights and permissions to collect and use such information.</p><p>You should not enter sensitive personal information into mysales unless the relevant feature specifically requires it and you have a lawful basis for doing so.</p>
<h2>8. Data Retention</h2><p>We retain information for as long as necessary to provide our services, maintain business records, comply with legal obligations, resolve disputes, and enforce our agreements.</p><p>You may request deletion of your account and associated personal information, subject to information that we are legally required to retain.</p>
<h2>9. Account and Data Deletion</h2><p>You may request deletion of your account and personal information by contacting us. Upon receiving a valid request, we will take reasonable steps to delete or anonymize your information, subject to applicable legal and regulatory requirements.</p>
<h2>10. Children's Privacy</h2><p>mysales is intended for business users and is not directed toward children. We do not knowingly collect personal information from children without appropriate authorization.</p>
<h2>11. Third-Party Services</h2><p>mysales may use third-party services to provide hosting, authentication, analytics, payments, notifications, or other functionality. These providers may process information according to their own privacy policies.</p>
<h2>12. Changes to This Privacy Policy</h2><p>We may update this Privacy Policy from time to time. When we make changes, we will update the "Last Updated" date at the top of this page. We encourage you to periodically review this Privacy Policy.</p>
<h2>13. Contact Us</h2><p>If you have questions, concerns, or requests regarding this Privacy Policy or your personal information, please contact us at:</p><p><strong>Email:</strong> <a href="mailto:ifiokabasiudoe@gmail.com">ifiokabasiudoe@gmail.com</a><br/><strong>App:</strong> mysales<br/><strong>Country:</strong> Nigeria</p></main>
  <footer className="legal-footer">© 2026 MySales. All rights reserved. <Link href="/terms">Terms</Link><Link href="/privacy-policy">Privacy Policy</Link></footer>
 </>;
}
