"use client";
import {FormEvent,useEffect,useState} from "react";
import {ArrowRight,Check,Mail,Menu,Smartphone,Users,X,Package,ReceiptText,WalletCards,UserRound,PieChart,BarChart3,Store,Utensils,Shirt,GraduationCap,MoreHorizontal,Bell,TrendingUp} from "lucide-react";

function WaitlistModal({open,onClose}:{open:boolean;onClose:()=>void}){
 const [form,setForm]=useState({name:"",phone:"",email:""}),[status,setStatus]=useState<"idle"|"loading"|"success"|"error">("idle"),[message,setMessage]=useState("");
 useEffect(()=>{if(!open)return;const f=(e:KeyboardEvent)=>e.key==="Escape"&&onClose();document.addEventListener("keydown",f);document.body.style.overflow="hidden";return()=>{document.removeEventListener("keydown",f);document.body.style.overflow=""}},[open,onClose]);
 if(!open)return null;
 async function submit(e:FormEvent){e.preventDefault();setStatus("loading");try{const r=await fetch("/api/waitlist",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)}),d=await r.json();if(!r.ok||!d.success)throw new Error(d.message||"Something went wrong.");setStatus("success");setMessage("You're on the waitlist!");setForm({name:"",phone:"",email:""})}catch(e){setStatus("error");setMessage(e instanceof Error?e.message:"Please try again.")}}
 return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><div className="waitlist-modal" role="dialog" aria-modal="true">
  <button className="modal-close" onClick={onClose}><X size={20}/></button>
  {status==="success"?<div className="success-view"><div className="success-icon"><Check size={30}/></div><div className="modal-eyebrow">WELCOME TO MYSALES</div><h2>You're on the list!</h2><p>Thanks for joining. We'll be among the first to let you know when MySales is ready.</p><button className="modal-submit" onClick={onClose}>Done</button></div>:
  <><div className="modal-logo">my<span>sales</span></div><div className="modal-eyebrow">COMING SOON</div><h2>Join the MySales waitlist.</h2><p className="modal-intro">Be among the first to use simple business software built for businesses looking to go places.</p>
  <form onSubmit={submit} className="modal-form">
   <label>Full name<div className="modal-field"><Users size={18}/><input required placeholder="Enter your full name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></div></label>
   <label>Phone number<div className="modal-field"><Smartphone size={18}/><input required type="tel" placeholder="0801 234 5678" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></div></label>
   <label>Email address<div className="modal-field"><Mail size={18}/><input required type="email" placeholder="you@example.com" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></div></label>
   <button className="modal-submit" disabled={status==="loading"}>{status==="loading"?"Joining...":"Join the Waitlist"}{status!=="loading"&&<ArrowRight size={18}/>}</button>
   {status==="error"&&<div className="modal-error">{message}</div>}<small className="modal-privacy">By joining, you agree to receive updates about MySales. We won't spam you.</small>
  </form></>}
 </div></div>
}

function JoinButton({onClick,children="Join Waitlist",light=false}:{onClick:()=>void;children?:React.ReactNode;light?:boolean}){return <button className={light?"button light-button":"button"} onClick={onClick}>{children}<ArrowRight size={16}/></button>}
function Feature({icon,title,text}:{icon:React.ReactNode;title:string;text:string}){return <div className="feature-card"><div className="feature-icon">{icon}</div><h3>{title}</h3><p>{text}</p></div>}
function HowStep({icon,number,title,text}:{icon:React.ReactNode;number:string;title:string;text:string}){return <div className="how-step"><div className="how-icon">{icon}</div><div><b>{number} {title}</b><p>{text}</p></div></div>}

function PhoneMockup(){return <div className="phone"><div className="phone-notch"/><div className="phone-screen"><div className="phone-top"><Menu size={17}/><strong>DEMO BUSINESS</strong><span className="phone-avatar">T</span></div><div className="phone-heading">Dashboard</div><div className="phone-subheading">Overview of your business</div><div className="phone-filters"><span>Today⌄</span><span>Main Branch⌄</span><span>↻</span></div>{[["Sales Today","₦256,450","↗ 12% from yesterday"],["Cost of Goods Sold","₦98,750","↗ 8.3% from yesterday"],["Gross Profit","₦157,700","↗ 10% from yesterday"],["Net Profit","₦112,200","↗ 9.4% from yesterday"]].map(x=><div className="phone-stat" key={x[0]}><div><small>{x[0]}</small><b>{x[1]}</b><em>{x[2]}</em></div><span>◉</span></div>)}<div className="quick-title">Quick Actions</div><div className="quick-actions"><div><Package/><small>Products</small></div><div><ReceiptText/><small>Purchases</small></div><div><Store/><small>Sales</small></div><div><BarChart3/><small>Reports</small></div></div></div></div>}

function ReceiptCard(){return <div className="receipt"><div className="receipt-title">MySales</div><div className="receipt-meta">Receipt #SALE-000006<br/>6/19/2026 · 3:41:29 AM</div><div className="receipt-line"/>{["2 Bottles of Mirinda - Lemon x ₦500|₦1,000","1 Bottle of Apple - Lemon x ₦600|₦600","3 Carton (6s) of Mirinda - Lemon x ₦2,800|₦8,400","3 Carton (6s) of Mirinda - Lemon x ₦5,200|₦15,600","3 Carton (12s) of Mirinda - Lemon x ₦5,600|₦16,800"].map(x=>{const a=x.split("|");return <p key={x}>{a[0]}<b>{a[1]}</b></p>})}<div className="receipt-line"/><p>Subtotal <b>₦42,400</b></p><h4>TOTAL <strong>₦42,400</strong></h4><div className="payment"><b>Payments</b><br/>Cash <strong>₦21,200</strong><br/>Transfer <strong>₦21,200</strong><br/>Total Paid <strong>₦42,400</strong><br/>Balance <strong>₦0</strong></div><div className="receipt-status">Status: paid</div><div className="receipt-thanks">Thank you for your purchase!</div><div className="receipt-actions"><button>Share</button><button>Print</button></div></div>}

export default function Home(){
 const [modalOpen,setModalOpen]=useState(false),[mobileOpen,setMobileOpen]=useState(false),open=()=>{setMobileOpen(false);setModalOpen(true)};
 return <main><WaitlistModal open={modalOpen} onClose={()=>setModalOpen(false)}/>
 <div className="topbar">Free to start for a month. When the month is over? <b>You only need ₦500 to continue.</b></div>
 <nav className="navbar"><a className="brand" href="#"><span className="brand-mark">M</span><span>MY<span>SALES</span></span></a><div className={`nav-links ${mobileOpen?"mobile-show":""}`}><a href="#features">Features</a><a href="#how">How It Works</a><a href="#pricing">Pricing</a><a href="#about">About Us</a><a href="#faq">FAQ</a><button className="mobile-x" onClick={()=>setMobileOpen(false)}><X/></button></div><div className="nav-right"><JoinButton onClick={open}>Join Waitlist</JoinButton><button className="hamburger" onClick={()=>setMobileOpen(true)}><Menu/></button></div></nav>
 <section className="hero"><div className="hero-copy"><div className="coming">✣ &nbsp;COMING SOON</div><h1>Think business software is only for supermarkets? <span>It isn't.</span></h1><p>Whether you have a shop, pharmacy, restaurant, fashion store, or you're just starting out, keeping track of your business shouldn't be difficult.</p><button className="hero-email-button" onClick={open}><Mail size={18}/><span>Join the waitlist</span><ArrowRight size={17}/></button><div className="trust-row"><div className="avatar-stack"><i>O</i><i>A</i><i>K</i><i>J</i></div><div><b>2,000+ entrepreneurs</b><br/>already joined the waitlist</div></div><div className="benefits"><div><span><Smartphone/></span><b>Works on phone</b><small>Run your business anywhere</small></div><div><span><Check/></span><b>Easy to use</b><small>No tech skills needed</small></div><div><span>₦</span><b>Super affordable</b><small>All features at a price you can afford</small></div></div></div><div className="hero-device"><PhoneMockup/><div className="price-bubble"><small>Starting from</small><strong>₦500</strong><span>/month</span></div><div className="spark">⌁</div></div></section>
 <section id="about" className="business-section"><div className="business-copy"><h2>You don't need a million-naira business to <span>manage your business like one.</span></h2><p>Start with the business you have today. MySales helps you keep records, track profits and make smarter decisions.</p><div className="business-types">{[["Shops",<Store/>],["Pharmacies",<span>+</span>],["Restaurants",<Utensils/>],["Boutiques",<Shirt/>],["Schools",<GraduationCap/>],["And more",<MoreHorizontal/>]].map(([x,icon])=><div key={x as string}>{icon}<small>{x}</small></div>)}</div></div><ReceiptCard/></section>
 <section id="features" className="features"><h2>Everything you need to run your business</h2><p>Powerful features. Simple to use.</p><div className="feature-grid"><Feature icon={<BarChart3/>} title="Track Sales" text="Record every sale and know exactly what you made."/><Feature icon={<Package/>} title="Manage Inventory" text="Know what's in stock and get low stock alerts."/><Feature icon={<ReceiptText/>} title="Print Receipts" text="Send or print professional receipts in seconds."/><Feature icon={<WalletCards/>} title="Track Expenses" text="Record all your business expenses in one place."/><Feature icon={<UserRound/>} title="Manage Customers" text="Keep customer information and build relationships."/><Feature icon={<PieChart/>} title="View Reports" text="See insights and make better decisions."/></div><button className="see-more" onClick={open}>See all features <ArrowRight size={15}/></button></section>
 <section id="pricing" className="pricing-banner"><div className="wallet-illustration">₦</div><div className="pricing-copy"><b>Powerful business tools.</b><span>Starting from just</span><strong>₦500 <small>/month</small></strong></div><div className="pricing-points"><div><Check/> One month free</div><div><Check/> No dollar card needed</div><div><Check/> Cancel anytime</div><div><Check/> All essential features included</div></div><JoinButton onClick={open} light>Join the Waitlist</JoinButton></section>
 <section id="how" className="how"><h2>How it works</h2><div className="how-grid"><HowStep icon={<Mail/>} number="1." title="Join the waitlist" text="Enter your details to get early access."/><HowStep icon={<Bell/>} number="2." title="We notify you" text="Be the first to know when we launch."/><HowStep icon={<Smartphone/>} number="3." title="Get started" text="Set up your business in just a few minutes."/><HowStep icon={<TrendingUp/>} number="4." title="Grow with confidence" text="Track, manage and grow your business."/></div></section>
 <footer><div className="footer-main"><div className="footer-brand"><a className="brand" href="#"><span className="brand-mark">M</span><span>MY<span>SALES</span></span></a><p>Track every sale.<br/>Understand your business.<br/>Grow with confidence.</p><div className="socials"><span>f</span><span>◎</span><span>𝕏</span><span>▶</span></div></div><div><b>Product</b><a href="#features">Features</a><a href="#how">How It Works</a><a href="#pricing">Pricing</a><a href="#">Updates</a></div><div><b>Company</b><a href="#about">About Us</a><a href="#">Contact Us</a><a href="#">Blog</a><a href="#">Careers</a></div><div><b>Legal</b><a href="#">Terms of Service</a><a href="#">Privacy Policy</a><a href="#">Refund Policy</a></div><div className="footer-join"><b>Join our waitlist</b><span>Be the first to know when MySales launches.</span><JoinButton onClick={open}>Join the Waitlist</JoinButton></div></div><div className="footer-bottom">© 2026 MySales. All rights reserved.<span>Built in Nigeria 🇳🇬 for African businesses.</span></div></footer>
 </main>
}