import Link from "next/link";

export const metadata = { title: "Terms and Conditions | MySales", description: "Terms and Conditions for MySales." };

export default function LegalPage() {
 return <>
  <header className="legal-nav"><Link href="/" className="legal-brand"><span className="legal-mark">M</span><span>MY<span>SALES</span></span></Link><Link href="/" className="legal-back">← Back to MySales</Link></header>
  <main className="legal-page"><h1>Terms and Conditions</h1>
<p className="legal-updated"><strong>Last Updated: August 9, 2026</strong></p>
<h2>1. Acceptance of These Terms</h2><p>Welcome to <strong>mysales</strong> ("mysales", "we", "our", or "us"). These Terms and Conditions ("Terms") govern your access to and use of the mysales mobile application, website, and related services (collectively, the "Service").</p><p>By creating an account, accessing, or using mysales, you agree to be bound by these Terms. If you do not agree with these Terms, you should not use the Service.</p>
<h2>2. About mysales</h2><p>mysales is a business management application designed to help businesses manage activities such as:</p><ul><li>Recording sales</li><li>Creating receipts</li><li>Managing products and inventory</li><li>Managing customers</li><li>Tracking business transactions</li><li>Managing staff and business users</li><li>Reviewing business records and reports</li><li>Other business-management functions provided within the Service</li></ul><p>mysales is a software tool and does not guarantee the profitability, financial performance, or success of any business.</p>
<h2>3. Eligibility</h2><p>You must be legally capable of entering into a binding agreement to use mysales. If you are using mysales on behalf of a business or organization, you confirm that you have the authority to accept these Terms on behalf of that business or organization.</p>
<h2>4. Creating an Account</h2><p>Some features of mysales may require you to create an account. You agree to provide accurate and current information, keep your account information up to date, protect your login credentials, not share your account credentials with unauthorized persons, and notify us if you believe your account has been compromised.</p><p>You are responsible for activities performed through your account unless they result from unauthorized access caused by circumstances outside your reasonable control.</p>
<h2>5. Business and Transaction Data</h2><p>mysales allows you to enter and store business information, including sales records, product information, inventory data, customer information, staff information, and other business records.</p><p>You retain responsibility for the accuracy, legality, and completeness of information you enter into mysales. mysales is not responsible for losses resulting from inaccurate information entered by you or your authorized users.</p><p>You should regularly review your business records and maintain appropriate backups of important information where necessary.</p>
<h2>6. Customer and Third-Party Information</h2><p>If you enter information about customers, employees, suppliers, or other individuals into mysales, you are responsible for ensuring that you have the appropriate legal basis, permission, or authority to collect and use that information.</p><p>You must not use mysales to unlawfully collect, store, distribute, or misuse another person's personal information.</p>
<h2>7. Acceptable Use</h2><p>You agree not to use mysales to violate applicable laws or regulations, commit fraud, impersonate another person or business, gain unauthorized access to another user's account, interfere with our systems, upload malicious software or harmful code, abuse or overload the Service, reverse engineer or exploit the Service except where permitted by law, or conduct activities that could harm mysales, its users, or third parties.</p><p>We reserve the right to restrict or terminate accounts that violate these Terms.</p>
<h2>8. Subscription and Fees</h2><p>mysales may offer free trials, promotional periods, subscriptions, or paid features. Applicable pricing, subscription period, and payment requirements will be presented before you purchase or activate a paid service.</p><ul><li>Subscription fees are charged according to the applicable billing period.</li><li>You are responsible for applicable taxes or charges associated with your purchase.</li><li>Prices may change in the future, but changes will not retroactively affect payments already completed.</li><li>Promotional offers may have additional terms and may be changed or withdrawn at any time.</li></ul>
<h2>9. Payments</h2><p>Payments for mysales services may be processed through third-party payment providers. You agree to provide accurate payment information where required. We do not guarantee that every payment method will always be available. Payment processing may also be subject to the terms and privacy policies of the applicable payment provider.</p>
<h2>10. Cancellation</h2><p>Where applicable, you may cancel your subscription through the method provided by mysales or the platform through which you purchased the subscription. Cancellation may prevent future charges but does not necessarily entitle you to a refund for a billing period that has already started. Any refund rights required by applicable law remain unaffected.</p>
<h2>11. Refunds</h2><p>Refunds will be handled according to the applicable refund policy and applicable law. Where a purchase is made through a third-party platform, such as an app store, refunds may be subject to that platform's refund rules. We may consider refund requests on a case-by-case basis where appropriate.</p>
<h2>12. Service Availability</h2><p>We aim to keep mysales available and reliable, but we do not guarantee that the Service will always be available without interruption, error-free, completely secure, or free from bugs or technical problems.</p><p>The Service may occasionally be unavailable because of maintenance, updates, technical failures, internet problems, third-party service failures, or circumstances beyond our control.</p>
<h2>13. Data and Backups</h2><p>While we take reasonable steps to protect and maintain your information, no digital storage system is completely immune to data loss, corruption, unauthorized access, or technical failure.</p><p>You are responsible for maintaining appropriate backups of critical business information where necessary. We are not responsible for business losses resulting solely from your failure to maintain appropriate records or backups.</p>
<h2>14. Intellectual Property</h2><p>The mysales application, including its software, design, branding, logos, graphics, interfaces, text, features, and other content provided by us, is owned by or licensed to mysales and is protected by applicable intellectual property laws.</p><p>You are granted a limited, non-exclusive, non-transferable right to use mysales for its intended purpose while you comply with these Terms.</p>
<h2>15. Your Content</h2><p>You retain ownership of business information and other content that you submit to mysales. By using the Service, you grant mysales the limited rights necessary to host, store, process, display, and otherwise handle your content solely for the purpose of providing and improving the Service, subject to our Privacy Policy.</p>
<h2>16. Third-Party Services</h2><p>mysales may integrate with or rely on third-party services, including payment providers, cloud infrastructure providers, authentication services, analytics providers, messaging services, or other technology providers. Third-party services may have their own terms and privacy policies.</p><p>We are not responsible for the independent actions, availability, or policies of third-party services.</p>
<h2>17. Business Decisions and Financial Information</h2><p>mysales may provide reports, calculations, summaries, analytics, or other information based on the data you enter. Such information is provided as a business-management aid and should not be considered professional accounting, tax, legal, investment, or financial advice.</p><p>You are responsible for verifying important financial, tax, accounting, and business information before making decisions based on it.</p>
<h2>18. No Guarantee of Business Results</h2><p>mysales does not guarantee that using the Service will increase your sales, reduce expenses, improve profits, prevent losses, or produce any particular business result.</p>
<h2>19. Account Suspension or Termination</h2><p>We may suspend, restrict, or terminate your access to mysales if you materially violate these Terms, engage in fraudulent or abusive activity, create a security risk, use the account for unlawful activities, fail to pay applicable fees, are required to do so by law, or if we discontinue the relevant Service.</p>
<h2>20. Effect of Termination</h2><p>When your account is terminated or you stop using mysales, your right to access the Service may end. Certain provisions of these Terms may continue to apply after termination, including provisions relating to intellectual property, limitations of liability, disputes, and other provisions that by their nature should survive termination.</p>
<h2>21. Limitation of Liability</h2><p>To the maximum extent permitted by applicable law, mysales and its owners, employees, affiliates, partners, and service providers will not be liable for indirect, incidental, special, consequential, or punitive damages arising from your use of or inability to use the Service.</p><p>This may include loss of profits, loss of revenue, loss of business opportunities, loss of data, or business interruption. Nothing in these Terms excludes or limits liability that cannot legally be excluded or limited under applicable law.</p>
<h2>22. Indemnification</h2><p>To the extent permitted by applicable law, you agree to indemnify and hold harmless mysales and its owners, employees, affiliates, and service providers from claims, losses, liabilities, damages, and expenses arising from your violation of these Terms, unlawful use of the Service, misuse of customer or third-party information, content or information you submit through the Service, or violation of another person's rights.</p>
<h2>23. Changes to the Service</h2><p>We may modify, add, remove, or discontinue features of mysales from time to time. We may also release updates, improvements, or changes to the application.</p>
<h2>24. Changes to These Terms</h2><p>We may update these Terms from time to time. When we make significant changes, we may notify users through the application, website, email, or other appropriate means. Your continued use of mysales after the updated Terms become effective constitutes acceptance of the revised Terms.</p>
<h2>25. Privacy</h2><p>Your use of mysales is also governed by our Privacy Policy, which explains how we collect, use, store, and protect personal information. The Privacy Policy forms part of these Terms.</p>
<h2>26. Governing Law</h2><p>These Terms shall be governed by and interpreted in accordance with the laws applicable in the Federal Republic of Nigeria, without regard to conflict-of-law principles. Any disputes shall be handled in accordance with applicable Nigerian law and the jurisdiction of the appropriate courts.</p>
<h2>27. Severability</h2><p>If any provision of these Terms is found to be invalid or unenforceable, the remaining provisions will continue to apply.</p>
<h2>28. Entire Agreement</h2><p>These Terms, together with our Privacy Policy and any other applicable policies or agreements referenced within the Service, constitute the agreement between you and mysales regarding your use of the Service.</p>
<h2>29. Contact Us</h2><p>If you have questions regarding these Terms and Conditions, you can contact us at:</p><p><strong>Email:</strong> <a href="mailto:ifiokabasiudoe@gmail.com">ifiokabasiudoe@gmail.com</a><br/><strong>App:</strong> mysales<br/><strong>Country:</strong> Nigeria</p></main>
  <footer className="legal-footer">© 2026 MySales. All rights reserved. <Link href="/terms">Terms</Link><Link href="/privacy-policy">Privacy Policy</Link></footer>
 </>;
}
